
# (PART) Getting started {-}

# Cloning the R sources

## Fetching R as a Git-SVN Repository

R is hosted on the [Subversion](https://en.wikipedia.org/wiki/Apache_Subversion) (SVN) version control system. In the age of github and gitlab, this can be a hindrance for most new developers who are only familiar with git workflows. Fortunately it is easy to interoperate with an SVN server (almost) as if it were a git repository. This is what we'll do.

Start by cloning R from Winston Chang's [git mirror](https://github.com/wch/r-source) of the Subversion repository:

```sh
git clone https://github.com/wch/r-source.git
```

Next we transform the git repository to a [git-svn](https://git-scm.com/docs/git-svn) one. A git-svn workflow is slightly different to regular git, but it will save you pain[^svn-checkout].

[^svn-checkout]: As of revision [62183](https://github.com/wch/r-source/commit/4f13e532), R must either be built from an SVN checkout or from the tarball generated by `make dist`. There is a [workaround](https://github.com/wch/r-source/wiki#adding-svn-information), but it seems to only work if you build R from the root directory. Building from the root is fine as a stopgap but we strongly recommend building R inside a separate directory.

```sh
cd r-source

# Prefix should match remote repo name with a trailing slash
git svn init --prefix=origin/ -s https://svn.r-project.org/R/
```

Now run the `info` command to finish the initialisation. This will cause git-svn to rebuild the `.rev_map` files that map the SVN revision numbers to git commits:

```sh
git svn info
```

Running it again should be instantenous and output something similar to this:

```
Path: .
URL: https://svn.r-project.org/R/trunk
Repository Root: https://svn.r-project.org/R
Repository UUID: 00db46b3-68df-0310-9c12-caf00c1e9a41
Revision: 77184
Node Kind: directory
Schedule: normal
Last Changed Author: pd
Last Changed Rev: 77184
Last Changed Date: 2019-09-13 01:19:45 +0200 (Fri, 13 Sep 2019)
```


## The Git-SVN workflow

Git-svn repositories work a little differently than normal git repos because SVN has no support for non-linear history. To work around this, git-svn commands avoid any pulling or merging. While it is fine to create branches and rebase, you should also avoid pulling and merging into SVN-controlled branches (like `trunk`) as this can mess up the git-svn repository[^pulling]. In particular, do not pull again from Winston's mirror to fetch the last updates. If git-svn complains with _Unable to determine upstream SVN information from working tree history_, that's probably because you've used `git pull`.

[^pulling]: It seems to work most of the time but we have sporadically
encountered issues, hence our recommendation to avoid pulling.

The main command to know about is `rebase`. It fetches new revisions from from the `trunk` branch on the SVN server, transforms them to git commit, and rebases any unpushed commits on top of them. This is how you'll update your repository to the latest sources:

```sh
git svn rebase
```

Another important command is `fetch`. Unlike `rebase` which only updates from `trunk`, `fetch` retrieves the revisions for all the branches saved in the SVN repository. __Note:__ This command takes a long time the first time you run it, you might want to do it overnight.

```sh
git svn fetch
```

Besides these two commands, you can use git as you would normally. You can create branches, rebase them, push them on github, etc.


# Building R

## Autotools

If you have ever compiled an open source project from scratch, you should be familiar with the file layout of `r-source`:

```sh
ls
#> COPYING         Makefile.fw     VERSION-NICK    doc/            share/
#> ChangeLog       Makefile.in     config.site     etc/            src/
#> INSTALL         README          configure       m4/             tests/
#> Makeconf.in     VERSION         configure.ac    po/             tools/
```

R is configured for your system and built into binaries using the [Autotools](https://en.wikipedia.org/wiki/GNU_Build_System) build system. Two important Autotools files are:

* `configure`: This is an executable script that configures the build system for your particular machine.

* `Makefile.in`: From this template, the configure script creates a `Makefile`. This file contains instructions for the command `make`, which is the workhorse of a build system.

Normally you build open source softwares with the following incantation (do not run this just yet, wait after reading the next section):

```sh
./configure && make && make install
```

For building R you need an additional step. First install the recommended packages:

```sh
# Download recommended packages
tools/rsync-recommended

./configure && make all && make install
```


## The build directory {#sec:build}

Running `configure` and `make` inside the root directory of the R sources is not very practical because they create files all over the place. These files can't be gitignored effectively and will get in the way of your workflow. To avoid littering the repository with generated files, we are going to build R from a separate directory.

The build directory can be created anywhere you like. Here we'll create it inside the repository and gitignore it:

```sh
mkdir build
echo "build/" >> .git/info/exclude
```

Now we configure the build by calling the configure script from inside the build directory:

```sh
cd build
../configure
```

This should take a couple of minutes. Once configured, your build directory looks like this:

```sh
ls
#> Makeconf                Makefrag.m              libconftest.dSYM/       src/
#> Makefile                config.log              libtool                 tests/
#> Makefrag.cc             config.status           m4/                     tools/
#> Makefrag.cc_lo          doc/                    po/
#> Makefrag.cxx            etc/                    share/
```

You'll recognise the `Makefile` file we mentioned earlier. You'll also find several directories mirroring the file hierarchy from the root folder. The most important are `src` and `tests`. These directories contain makefiles of their own:

```sh
ls src
#> Makefile        extra/          library/        modules/        scripts/
#> appl/           include/        main/           nmath/          unix/

ls tests
#> Embedding/      Examples/       Makefile
```

Given the similarity of the file hierarchies it is easy to confuse the __root__ and __build__ directories.

* The root directory contains all the sources, saved outputs for unit tests, and other revisioned files. You will develop from the root directory.

* The build directory contains all the makefiles that allow you to interact with the build system. From the build directory you'll build R, recompile parts of R, run tests, etc.


## Location of installation

We have run `configure` but we haven't specified any parameter. You can discover all the supported options with:

```sh
../configure --help
```

One important parameter is the location where you'd like to install R. It is normally decided by the `--prefix=path` argument.

```sh
../configure --prefix=/usr/local
```

On macOS systems it is often more practical to install R as an application framework. In that case, you don't supply `--prefix` but `--enable-R-framework`. The advantage of installing as a framework is that you can use the convenient [RSwitch](https://rud.is/rswitch/) dropdown menu to switch to the development version.

```sh
../configure --enable-R-framework
```


## Environment variables

`configure --help` lists all influential environment variables. You can set envvars by passing them to the configure script. For instance, we might want to set `CFLAGS` to enable debugging symbols and disable compiler optimisations. This considerably improves the debugging experience:

```sh
../configure CFLAGS="-g -O0"
```

Other important envvars are:

* `CPPFLAGS` and `LDFLAGS`. By default they point to `/usr/local/include` and `/usr/local/lib`. On macOS systems, this is where libraries installed with `brew` are linked.

* `CC` which points to `gcc` by default. On macOS systems, this is an alias for the system `clang`.


## Making R on macOS

I personally use the following script to build R on macOS. It should be run from the build directory, and the build directory should be a folder inside the root directory:

```sh
#!/bin/bash
​
​
# R recommends setting this to avoid issues with programs like sed:
export LANG=C

export R_ARCH=""
​
# Get version in major.minor format:
VERSION=`sed 's/\([0-9]*.[0-9]*\).[0-9]*.*/\1/' ../VERSION`
​
# Use version-dev as default folder target:
TARGET=${1:-$VERSION-dev}
​
​
# Download recommended packages
../tools/rsync-recommended
​
../configure \
    --enable-R-framework FW_VERSION=${TARGET} \
    --with-aqua=yes \
    --with-x=yes \
    --enable-memory-profiling \
    CFLAGS="-g -O0" && \
  make all && \
  make install
```

This script:

* Installs R as an application framework whose version is suffixed with `-dev`. The suffix is useful if you'd like to install a patched version of an already released R. If you're working exclusively on the development version, this is not as useful since the framework is set to the next unreleased version and cannot interfere with your regular installations.

* Installs the recommended packages. These packages are needed for running unit tests.

* Enables Aqua and X. This adds some compilation time but is useful if you plan to use the development version for actual data analysis or if you'd like to patch the graphical devices.

* Enables the R memory profiler.

* Sets `CFLAGS` to include debugging symbols and disable optimisations.

* Runs `make all` to build R and `make install` to install it as a framework.

The framework is automatically enabled after `make install`. You should get the following disclaimer if you run R:

```sh
R
#> R Under development (unstable) (2019-09-12 r77181) -- "Unsuffered Consequences"
#> Copyright (C) 2019 The R Foundation for Statistical Computing
#> Platform: x86_64-apple-darwin18.0.0 (64-bit)
```

### Compilation troubleshooting

*   liblzma library and headers are required

    ```sh
    brew install xz
    ```

*   zlib library and headers are required

    ```sh
    brew install zlib
    ```

*   configure error: cannot run C compiled programs

    ```sh
    xcode-select --install
    ```
