#!/bin/bash

# 2022-06-24 Tue 16:33
#
# Generate SVN-REVISION file from the last git-svn commit in the current branch.

BUILD_DIR=$(pwd)

# Switch to the repo so that `git` commands work. Stay in the build
# dir by default, but this only works if `build` is a subdirectory
# inside the repo.
SRC_DIR=${1-$BUILD_DIR}
cd ${SRC_DIR}

echo -n 'Revision: ' \
    > ${BUILD_DIR}/SVN-REVISION

git log --grep='git-svn-id' -n 1 --format=%B \
    | grep "^git-svn-id"    \
    | sed -E 's/^git-svn-id: https:\/\/svn.r-project.org\/R\/[^@]*@([0-9]+).*$/\1/' \
    >> ${BUILD_DIR}/SVN-REVISION

echo -n 'Last Changed Date: ' \
    >> ${BUILD_DIR}/SVN-REVISION

git log --grep='git-svn-id' -n 1 --pretty=format:"%ad" --date=iso \
    | cut -d' ' -f1 \
    >> ${BUILD_DIR}/SVN-REVISION
